### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by YWzheng** [yydcdut/PhotoNoter#1]
主界面Activity，没有配置特定的加载模式，导致几个页面跳转之后，需要按好多次返回键，才能退出程序

**Comment by yydcdut** [comment]
没看明白啊，主界面退出是要按两次返回，跳转其他页面后退出程序不应该一个个页面关闭吗？

**Comment by YWzheng** [comment]
不好意思，可能是我手机的问题，重新运行后没问题了
