### ISSUE TITLE
debug下没有找到对应的allclasses.jar

### ISSUE THREAD

**Issue by zhuangjiahua** [yydcdut/PhotoNoter#10]
//build/intermediates/multi-dex/Store360/debug/allclasses.jar
    def jarDebugPath = "${projectDir}${File.separator}" +
            "build${File.separator}" +
            "intermediates${File.separator}" +
            "multi-dex${File.separator}" +
            "${flavor}${File.separator}" +
            "${buildType}${File.separator}" +
            "allclasses.jar"

环境:Android Studio 2.1、Gradle 2.10

**Comment by yydcdut** [comment]
@zhuangjiahua 
Gradle得换1.4以下的，1.5之后打包的形式改了

**Comment by zhuangjiahua** [comment]
谢谢
