### ISSUE TITLE
请问将gradle1.3.0、dex分包脚本均注释掉。使用gradle2.1.0是何解？

### ISSUE THREAD

**Issue by williamsim** [yydcdut/PhotoNoter#12]
请问将gradle1.3.0、dex分包脚本均注释掉。使用gradle2.1.0是何解？

**Comment by yydcdut** [comment]
之前加了滤镜等许多SDK之后，就需要分包了，所以那个时候用1.3.0，进行了处理。
现在我将那部分SDK代码抽出来了，打算使用插件化，代码编译出来只有1个dex，就无需进行dex分包处理，使用2.1.0用instantRun加快开发效率。

**Comment by williamsim** [comment]
@yydcdut 对于如何使用dex.gradle我还是不太明白，还有关于multidex.keep如何生成，只要解开以下注释就可以了吗？
`//tasks.whenTaskAdded { task ->
//    if (task.name.startsWith("create") && task.name.endsWith("MainDexClassList")) {
//        task.doLast {
//            def flavorAndBuildType = task.name.substring("create".length(), task.name.length() - "MainDexClassList".length())
//            autoSplitDex.configure {
//                description = flavorAndBuildType
//            }
//            autoSplitDex.execute()
//        }
//    }
//}`

**Comment by yydcdut** [comment]
@williamsim 
http://yydcdut.com/2016/03/20/split-dex/
或许这个可以帮助你更加了解这部分
