### ISSUE TITLE
分包貌似没起作用啊？

### ISSUE THREAD

**Issue by yljjiava** [yydcdut/PhotoNoter#13]
如题，我复制你的部分配置如下：
 afterEvaluate {
    tasks.matching {
        it.name.startsWith('dex')
    }.each { dx ->
        if (dx.additionalParameters == null) {
            dx.additionalParameters = []
        }
        dx.additionalParameters += '--multi-dex'
        dx.additionalParameters += '--set-max-idx-number=48000'
        //dx.additionalParameters += "--main-dex-list=$projectDir/multidex.keep".toString()
    }
}
我的gradle如下：
 dependencies {
        /**
         * 这里 build gradle、google-services 不能高于1.3.0，否则报以下错误:
         *   Error:(32, 0) Access to the dex task is now impossible, starting with 1.4.0
             1.4.0 introduces a new Transform API allowing manipulation of the .class files.
             See more information: http://tools.android.com/tech-docs/new-build-system/transform-api
             <a href="openFile:E:\android_stutio\DL2.0\app\build.gradle">Open File</a>
         */
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.google.gms:google-services:1.3.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

app/build.gradle
 
apply  plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply from: '../gradle/dex.gradle'
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.sailvan.dresslink"
        minSdkVersion 10
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        //配置为true，表示需要将dex分包，false则不分包
        multiDexEnabled true
        manifestPlaceholders = [
            GETUI_APP_ID : "Q2tMVHJtPm5PqbHo1n8vZ8",
            GETUI_APP_KEY : "k8rwPZy6E56bTCFEUQ1wa2",
            GETUI_APP_SECRET : "osfJrB3Xap8lilLxTMPmN6",
            PACKAGE_NAME : "com.sailvan.dresslink"
        ]
    }

    dexOptions {
        //设置虚拟机堆内存空间大小，避免在编译期间OOM
        javaMaxHeapSize "2g"
        preDexLibraries = false
    }

  /*  android.applicationVariants.all {
        variant ->
            dex.doFirst{
                dex->
                    if (dex.additionalParameters == null) {
                        dex.additionalParameters = []
                    }
                    //为了避免在2.2等低端机型上 linearAlloc的bug 这里控制linearAlloc大小<=4m
                    dex.additionalParameters += '--set-max-idx-number=48000'
            }
    }*/

    afterEvaluate {
    tasks.matching {
        it.name.startsWith('dex')
    }.each { dx ->
        if (dx.additionalParameters == null) {
            dx.additionalParameters = []
        }
        dx.additionalParameters += '--multi-dex'
        dx.additionalParameters += '--set-max-idx-number=48000'
        //dx.additionalParameters += "--main-dex-list=$projectDir/multidex.keep".toString()
    }
}
........

怎么最后apk中只有一个classes。dex文件，而上面注释的那种方式，限定gradle版本必须为1.3.0.请问一下在gradle2.1.2版本的话，配置该怎么写啊？

**Comment by yydcdut** [comment]
就像你上边写的
```
这里 build gradle、google-services 不能高于1.3.0，否则报以下错误:
* Error:(32, 0) Access to the dex task is now impossible, starting with 1.4.0
1.4.0 introduces a new Transform API allowing manipulation of the .class files.
See more information: http://tools.android.com/tech-docs/new-build-system/transform-api
Open File
```
2.1.2的话没有dex这个task，所以那些参数'--multi-dex'和'--set-max-idx-number=48000'没法实现。
如果你想在2.1.2控制dex文件里面的方法数的话，我目前还不知道解决方法
如果你像在2.1.2控制主dex里面的class的话，可以试试在defaultConfig中增加 multiDexKeepProguardfile("file.txt") 这种方法，file.txt里面的语法跟混淆的语法一样

**Comment by yljjiava** [comment]
谢谢解答，看你项目中分包的配置都被注释掉了，但是下载你的apk后发现是分包的。我想问问如果要分包，是不是在app/build.gradle文件做如下配置即可：
apply from: '../gradle/dex.gradle'
    afterEvaluate {
    tasks.matching {
        it.name.startsWith('dex')
    }.each { dx ->
        if (dx.additionalParameters == null) {
            dx.additionalParameters = []
        }
        dx.additionalParameters += '--multi-dex'
        dx.additionalParameters += '--set-max-idx-number=48000'
        //dx.additionalParameters += "--main-dex-list=$projectDir/multidex.keep".toString()
    }
}

tasks.whenTaskAdded { task ->
    if (task.name.startsWith("create") && task.name.endsWith("MainDexClassList")) {
        task.doLast {
            def flavorAndBuildType = task.name.substring("create".length(), task.name.length() - "MainDexClassList".length())
            autoSplitDex.configure {
                description = flavorAndBuildType
            }
            autoSplitDex.execute()
        }
    }
}

然后配合你写的dex。gradle就能完成指定主dex保留哪些class的操作。看了下dex.gralde文件代码量很大，一时没看懂，其实主要是想问：
1.  afterEvaluate {
    tasks.matching {
        it.name.startsWith('dex')
    }.each { dx ->
        if (dx.additionalParameters == null) {
            dx.additionalParameters = []
        }
        dx.additionalParameters += '--multi-dex'
        dx.additionalParameters += '--set-max-idx-number=48000'
        //dx.additionalParameters += "--main-dex-list=$projectDir/multidex.keep".toString()
    }
} 这段配置是不是控制分包，且每个dex方法数在48000？

2.tasks.whenTaskAdded { task ->
    if (task.name.startsWith("create") && task.name.endsWith("MainDexClassList")) {
        task.doLast {
            def flavorAndBuildType = task.name.substring("create".length(), task.name.length() - "MainDexClassList".length())
            autoSplitDex.configure {
                description = flavorAndBuildType
            }
            autoSplitDex.execute()
        }
    }
} 这段配置是不是找到主dex中需要的class文件？

**Comment by yydcdut** [comment]
对，是的。
因为后面我将几个SDK抽出来了，所以就不需要分包了，就注释掉了。

**Comment by yljjiava** [comment]
thanks a lot. 刚刚看到gradle 2.2.0-alpha4版本变更信息，可以支持如下配置来完成dex方法数控制：
2.2.0-alpha4 (2016/6/23)
Fixed instant-run regressions introduced in previous alpha builds related to code refactoring.
Turned off new packager by default due to some signing issues.
versionNameSuffix can now be specified for product flavors.
DexOptions now has an additionalParameters property for specifying custom flags for dx.
ProGuard files returned by getDefaultProguardFile are distributed with the plugin now, the ones in $ANDROID_HOME are no longer used.
SDK auto-download: Gradle will attempt to download missing SDK packages that a project depends on.
Added support for annotation processors. By default, annotation processors on your classpath, such as any compile dependency, will be automatically applied. You can also specify an annotation processor in your build and pass arguments by using the following DSL in your module-level build.gradle file:
android {
    defaultConfig {
        javaCompileOptions { 
            annotationProcessorOptions {
                className 'com.example.MyProcessor'

   // Arguments are optional.
                arguments = [ foo : 'bar' ]
            }
        }
    }
}
dx参数又会来了！

**Comment by yydcdut** [comment]
额，谢谢，没看明白，方便给一下链接吗？

**Comment by yljjiava** [comment]
http://tools.android.com/tech-docs/new-build-system

**Comment by yljjiava** [comment]
我在gradle的配置如下：
 dexOptions {
        //设置虚拟机堆内存空间大小，避免在编译期间OOM
        javaMaxHeapSize "2g"
        preDexLibraries = false
        additionalParameters=['--multi-dex','--set-max-idx-number=48000']
    }
我在一个工程这样配置可以成功分包运行应用，但是在另一个工程分包了，但是启动报NoClassDefFoundError错误，这个错误可以用你写的dex.gradle脚本解决吗？

**Comment by yydcdut** [comment]
谢谢！
我写的dex.gradle对我的那个项目针对性比较强
如果你要用在你的项目里面的话，试试将findNeededPresenters方法里面的内容替换成你的
而且这个脚本还有没有找出间接类的功能

**Comment by yljjiava** [comment]
哦，谢谢

**Comment by yljjiava** [comment]
顺便再问一下你这个分包是基于gradle插件1.4.0以下的吧？

**Comment by yydcdut** [comment]
额，是。
我这周再试试能不能在2.2.0-preview上实现吧

**Comment by yljjiava** [comment]
thanks,后续关注！

**Comment by yydcdut** [comment]
@yljjiava 
可以实现。
```groovy
    dexOptions {
        javaMaxHeapSize "4g"
        additionalParameters = ['--multi-dex',
                                '--set-max-idx-number=20000',
                                "--main-dex-list=$projectDir/multidex.keep".toString(),
                                "--minimal-main-dex"]
    }
```

```groovy
tasks.whenTaskAdded { task ->
    if (task.name.startsWith("transformClassesWithMultidexlistFor")) {
        task.doLast {
            def flavorAndBuildType = task.name.substring("transformClassesWithMultidexlistFor".length(), task.name.length())
            autoSplitDex.configure {
                description = flavorAndBuildType
            }
            autoSplitDex.execute()
        }
    }
}
```

目前测试debug的情况是通过的。

**Comment by yljjiava** [comment]
谢谢更新，已经查看了dex.build的改动，发现就jarDebugPath实现变了。还有问一下，findNeededPresenters这个方法里的类，是自己手动写上的吗？

**Comment by yydcdut** [comment]
@yljjiava 
对，但是有几个todo的地方需要注意一下，那些地方我还没有处理完。

**Comment by yljjiava** [comment]
ok
