### ISSUE TITLE
关于在gradle插件2.1.0后怎么通过gradle查找直接依赖问题？

### ISSUE THREAD

**Issue by yljjiava** [yydcdut/PhotoNoter#16]
博主好，之前我在https://github.com/yydcdut/PhotoNoter/issues/13这里发表过？现在这个问题关闭了，只能在这重发问，接着之前的问题，在dex.gradle文件中，之前博主也说过在2.2.0上实现没问题，只是有几个TODO的地方没实现，其中发现了两处：
1. //todo for test
    flavor = flavor.toLowerCase()  这个估计是test版本需要，所以可以不用实现。

2.def getDependentJava(File file, Set<String> packageJavaSet) {
    def content = readFile(file)
    def pattern = Pattern.compile("import *");//todo import *$ , XXXXXLINE
    def packageJavas = pattern.split(content);
    for (int i = 1; i < packageJavas.length - 1; i++) {
        def packageJava = packageJavas[i].trim()
        //系统的不要
        if (packageJava.startsWith("java") || (packageJava.startsWith("android") && !packageJava.startsWith("android.support"))
                || packageJava.startsWith(" ") || packageJava.startsWith("static")) {
            continue;
        } else {
            //去掉分号
            packageJavaSet.add(packageJava.substring(0, packageJava.length() - 1))
        }
    }
    def lastOne = packageJavas[packageJavas.length - 1]
    def lastPackage = lastOne.split("\n")[0]
    if (lastPackage.trim().startsWith("java") || (lastPackage.trim().startsWith("android") && !lastPackage.trim().startsWith("android.support"))
            || lastPackage.trim().startsWith(" ") || lastPackage.trim().startsWith("static")) {
        // do nothing
    } else {
        packageJavaSet.add(lastPackage.trim().substring(0, lastPackage.trim().length() - 1))
    }
}
在getDependentJava方法中//todo import *$ , XXXXXLINE，这里应该是寻找内部类，研究了下，由于对gradle掌握的不是很好，所以这里不敢轻易去实现，所以想问博主，这里具体要怎么实现呢？多多指教！

**Comment by yydcdut** [comment]
其实我在这里找内部类的方式就是通过读取源文件，然后找出import的类。方法不是只有这一种，有好多种，可以用javap反编译源代码然后找
