### ISSUE TITLE
大神，编译时出错了

### ISSUE THREAD

**Issue by StormPhoenix** [yydcdut/PhotoNoter#18]
在4.0的模拟器下编译安装出现如下错误：
java.lang.ClassNotFoundException: android.hardware.camera2.CameraAccessException
编译失败。

在6.0的模拟器下，显示
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class然后后面是一大堆error，不过最后能编译成功。。。

**Comment by yydcdut** [comment]
第一个问题是使用Dagger2初始化5.0才提供的API的时候导致的问题，这个问题之前就已经修复了。
