### ISSUE TITLE
crash in android M

### ISSUE THREAD

**Issue by xk009** [yydcdut/PhotoNoter#2]
When I use  gallery in your app in android M。It is crashed 。The reason crashed in gallery is that can't load photo files。below is the crash log.
![image](https://cloud.githubusercontent.com/assets/13362331/12111435/42957394-b3d0-11e5-9c15-9b3a490a9264.png)

It is also crash when i use take photo with camera. below is the crash log.
![image](https://cloud.githubusercontent.com/assets/13362331/12111471/861fc61e-b3d0-11e5-934d-4e0c55c5556e.png)

**Comment by yydcdut** [comment]
这是最新代码吗？这几天就是在做6.0的适配，gallery那部分已经处理得差不多了，可以再试一下~

**Comment by xk009** [comment]
gallery已经可以了。调用相机还是crash.

**Comment by yydcdut** [comment]
😉😉😉好了，更下代码试试呢，我在模拟器上弄的，不知道相机能不能运行

**Comment by xk009** [comment]
好了。。
