### ISSUE TITLE
你怎么分包的，给出可具体的操作说明可好？

### ISSUE THREAD

**Issue by nianzixin** [yydcdut/PhotoNoter#4]

**Comment by yydcdut** [comment]
`/app/multidex.keep`
在这个文件里面添加留在主dex里面的类
`/app/build.gradle`
把这句话的注释给取消掉
`dex.additionalParameters += "--main-dex-list=$projectDir/multidex.keep".toString()`

**Comment by yydcdut** [comment]
[分包脚本](https://github.com/yydcdut/PhotoNoter/blob/master/gradle/dex.gradle)
主包里面有Android的四大组件，以及需要找到依赖的组件。

**Comment by hyr0318** [comment]
@yydcdut  分包脚本 dex.gradle  怎么样使用额？  我按照上面的来 运行还是报NoClassDefFoundError。
