### ISSUE TITLE
拉下项目点击运行时报错

### ISSUE THREAD

**Issue by LeonJavaAndroid** [yydcdut/PhotoNoter#5]
Error:Execution failed for task ':app:compileStore360DebugNdk'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\ProgramFiles\android-ndk-r10d\ndk-build.cmd'' finished with non-zero exit value 2

请问这个要怎么解决？

**Comment by yydcdut** [comment]
@LeonJavaAndroid 
NDK版本换为r10e的再试试呢。

**Comment by tuzhao** [comment]
我曾经也出现这个错误，不过我是在ubuntu 14.04 LTS 64位上面出现的。
Android SDK中的adb程序是32位的，Ubuntu x64系统需要安装32位库文件，用于兼容32位的程序。
如果不安装，adb会出错：java.io.IOException: error=2
在terminal执行下面的安装即可：
sudo apt-get install -y libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1 --force-yes

**Comment by LeonJavaAndroid** [comment]
@yydcdut @tuzhao 
换为r10e后试过ok了
