### ISSUE TITLE
印象笔记不能同步，怎么回事

### ISSUE THREAD

**Issue by duanshengze** [yydcdut/PhotoNoter#8]

**Comment by yydcdut** [comment]
@duanshengze 
谢谢，刚刚修复了，UI操作放在子线程里面了。

**Comment by duanshengze** [comment]
1.高级相机照相不能保存
2.本地照片不能上传

**Comment by yydcdut** [comment]
@duanshengze 
谢谢，已经复现，我会尽快解决！

**Comment by yydcdut** [comment]
@duanshengze 
万分感谢！已经解决上述问题了。

**Comment by duanshengze** [comment]
我同步  但是我的印象笔记没有照片
![image](https://cloud.githubusercontent.com/assets/10880229/14767633/2d4859be-0a5d-11e6-98f4-46b59df5fc76.png)

**Comment by yydcdut** [comment]
@duanshengze 
更新之后的代码吗？我这边是有的。
